AKASN.1: akasn1.h File Reference
akasn1.h File Reference
#include "vlARGS.h"
Macros
#define MAXOID 10
#define asnFALSE 0x00
#define asnTRUE 0xFF
#define asnUNIVERSAL 0x00
#define asnAPPLICATION 0x40
#define asnCONTEXT 0x80
#define asnPRIVATE 0xC0
#define asnPRIMITIVE 0x00
#define asnCONSTRUCTED 0x20
#define asnINDEFINITE -1l
#define asnENDCONTENTS -2l
#define asnNOTHING 0x00
#define asnBOOLEAN 0x01
#define asnINTEGER 0x02
#define asnOCTETSTRING 0x04
#define asnNULLVALUE 0x05
#define asnOBJECTID 0x06
#define asnEXTERNAL 0x08
#define asnENUMERATED 0x0A
#define asnSEQUENCE 0x10
#define asnSET 0x11
#define asnNUMERICSTRING 0x12
#define asnPRINTABLESTRING 0x13
#define asnTELETEXSTRING 0x14
#define asnVIDEOTEXSTRING 0x15
#define asnIA5STRING 0x16
#define asnGRAPHICSTRING 0x19
#define asnVISIBLESTRING 0x1A
#define asnGENERALSTRING 0x1B
#define asnDecodeNumericString asnDecodeOctetString
#define asnEncodeNumericString(v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnNUMERICSTRING)
#define asnReadNumericString asnReadOctet
#define asnReadNumericStringL asnReadOctetL
#define asnReadNumericStringTL asnReadOctetTL
#define asnReadNumericStringFile asnReadOctetFile
#define asnReadNumericStringFileL asnReadOctetFileL
#define asnReadNumericStringFileTL asnReadOctetFileTL
#define asnWriteNumericString(v) _asnWriteOctet(v,strlen(v),asnNUMERICSTRING)
#define asnWriteNumericStringFile(f, l) _asnWriteOctetFile(f,l,asnNUMERICSTRING)
#define asnDecodePrintableString asnDecodeOctetString
#define asnEncodePrintableString(v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnPRINTABLESTRING)
#define asnReadPrintableString asnReadOctet
#define asnReadPrintableStringL asnReadOctetL
#define asnReadPrintableStringTL asnReadOctetTL
#define asnReadPrintableStringFile asnReadOctetFile
#define asnReadPrintableStringFileL asnReadOctetFileL
#define asnReadPrintableStringFileTL asnReadOctetFileTL
#define asnWritePrintableString(v) _asnWriteOctet(v,strlen(v),asnPRINTABLESTRING)
#define asnWritePrintableStringFile(f, l) _asnWriteOctetFile(f,l,asnPRINTABLESTRING)
#define asnDecodeTeletexString asnDecodeOctetString
#define asnEncodeTeletexString(v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnTELETEXSTRING)
#define asnReadTeletexString asnReadOctet
#define asnReadTeletexStringL asnReadOctetL
#define asnReadTeletexStringTL asnReadOctetTL
#define asnReadTeletexStringFile asnReadOctetFile
#define asnReadTeletexStringFileL asnReadOctetFileL
#define asnReadTeletexStringFileTL asnReadOctetFileTL
#define asnWriteTeletexString(v) _asnWriteOctet(v,strlen(v),asnTELETEXSTRING)
#define asnWriteTeletexStringFile(f, l) _asnWriteOctetFile(f,l,asnTELETEXSTRING)
#define asnDecodeVideotexString asnDecodeOctetString
#define asnEncodeVideotexString(v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnVIDEOTEXSTRING)
#define asnReadVideotexString asnReadOctet
#define asnReadVideotexStringL asnReadOctetL
#define asnReadVideotexStringTL asnReadOctetTL
#define asnReadVideotexStringFile asnReadOctetFile
#define asnReadVideotexStringFileL asnReadOctetFileL
#define asnReadVideotexStringFileTL asnReadOctetFileTL
#define asnWriteVideotexString(v) _asnWriteOctet(v,strlen(v),asnVIDEOTEXSTRING)
#define asnWriteVideotexStringFile(f, l) _asnWriteOctetFile(f,l,asnVIDEOTEXSTRING)
#define asnDecodeGraphicString asnDecodeOctetString
#define asnEncodeGraphicString(v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnGRAPHICSTRING)
#define asnReadGraphicString asnReadOctet
#define asnReadGraphicStringL asnReadOctetL
#define asnReadGraphicStringTL asnReadOctetTL
#define asnReadGraphicStringFile asnReadOctetFile
#define asnReadGraphicStringFileL asnReadOctetFileL
#define asnReadGraphicStringFileTL asnReadOctetFileTL
#define asnWriteGraphicString(v) _asnWriteOctet(v,strlen(v),asnGRAPHICSTRING)
#define asnWriteGraphicStringFile(f, l) _asnWriteOctetFile(f,l,asnGRAPHICSTRING)
#define asnDecodeVisibleString asnDecodeOctetString
#define asnEncodeVisibleString(v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnVISIBLESTRING)
#define asnReadVisibleString asnReadOctet
#define asnReadVisibleStringL asnReadOctetL
#define asnReadVisibleStringTL asnReadOctetTL
#define asnReadVisibleStringFile asnReadOctetFile
#define asnReadVisibleStringFileL asnReadOctetFileL
#define asnReadVisibleStringFileTL asnReadOctetFileTL
#define asnWriteVisibleString(v) _asnWriteOctet(v,strlen(v),asnVISIBLESTRING)
#define asnWriteVisibleStringFile(f, l) _asnWriteOctetFile(f,l,asnVISIBLESTRING)
#define asnDecodeGeneralString asnDecodeOctetString
#define asnEncodeGeneralString(v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnGENERALSTRING)
#define asnReadGeneralString asnReadOctet
#define asnReadGeneralStringL asnReadOctetL
#define asnReadGeneralStringTL asnReadOctetTL
#define asnReadGeneralStringFile asnReadOctetFile
#define asnReadGeneralStringFileL asnReadOctetFileL
#define asnReadGeneralStringFileTL asnReadOctetFileTL
#define asnWriteGeneralString(v) _asnWriteOctet(v,strlen(v),asnGENERALSTRING)
#define asnWriteGeneralStringFile(f, l) _asnWriteOctetFile(f,l,asnGENERALSTRING)
#define asnDecodeIA5String asnDecodeOctetString
#define asnEncodeIA5String(v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnIA5STRING)
#define asnReadIA5String asnReadOctet
#define asnReadIA5StringL asnReadOctetL
#define asnReadIA5StringTL asnReadOctetTL
#define asnReadIA5StringFile asnReadOctetFile
#define asnReadIA5StringFileL asnReadOctetFileL
#define asnReadIA5StringFileTL asnReadOctetFileTL
#define asnWriteIA5String(v) _asnWriteOctet(v,strlen(v),asnIA5STRING)
#define asnWriteIA5StringFile(f, l) _asnWriteOctetFile(f,l,asnIA5STRING)
#define asnWriteOctet(v, l) _asnWriteOctet (v,l,asnOCTETSTRING)
#define asnWriteOctetFile(f, l) _asnWriteOctetFile(f,l,asnOCTETSTRING)
Typedefs
typedef unsigned char byte
typedef unsigned int uint
Functions
EXTERN void asnCloseFile (void)
Close the opened ASN.1 file.
EXTERN int asnDecodeBoolean (byte *buffer, byte *value)
Decode a boolean value from a buffer.
EXTERN int asnDecodeEnum (byte *buffer, int length, long *value)
Decode an enumeration value.
EXTERN int asnDecodeLength (byte *buffer, long *length)
Decode a "length" field.
EXTERN int asnDecodeIA5 (byte *value, int length)
Decode an IA5-String.
EXTERN int asnDecodeInteger (byte *buffer, int length, long *value)
Decode an integer value.
EXTERN int asnDecodeOctet (byte *value, int length)
Decode an octet string from a buffer.
EXTERN int asnDecodeOid (byte *buffer, int len, char *id)
Decode an object identifier from a buffer into a string.
EXTERN int asnDecodeTag (byte *clasS, byte *pc, byte *tagnum, byte *buf)
Decode an ASN.1 tag.
EXTERN int asnEncodeBoolean (byte *buffer, byte value)
Encode a boolean value.
EXTERN int asnEncodeBooleanValue (byte *buffer, byte value)
Encode a boolean value.
EXTERN int asnEncodeEnum (byte *buffer, long value)
Encode an enumeration value with tag and length.
EXTERN int asnEncodeEnumValue (byte *buffer, long value)
Encode an enumeration value as an integer with tag and length.
EXTERN int asnEncodeIA5 (char *value, byte *buffer, int *length)
Encode an IA5-String with tag and length.
EXTERN int asnEncodeInteger (byte *buffer, long value)
Encode an integer value with tag and length.
EXTERN int asnEncodeIntegerValue (byte *buffer, long value)
Encode an integer value with tag (no length!)
EXTERN int asnEncodeLength (byte *buffer, long length)
Encode a "length" field.
EXTERN int asnEncodeNull (byte *buffer)
Encode a Null value.
EXTERN int asnEncodeOctet (byte *value, int length, byte *tag_len, int *tl_length, byte tag)
Encode an octet string with tag and length into a buffer.
EXTERN int asnEncodeOid (byte *buffer, char *id)
Encode an object identifier with the tag and length.
EXTERN int asnEncodeTag (byte *buf, byte clasS, byte pc, byte tag)
Encode an ASN.1 tag.
EXTERN int asnFseek (long pos)
Seek to a position pos in the open ASN.1-file.
EXTERN long asnFtell (void)
Get position in the opened ASN.1-File.
EXTERN int asnIsEOC (void)
Check for End-Of-Contents in the opened ASN.1 file.
EXTERN int asnOpenReadFile (char *fn)
Open an ASN.1 file for reading.
EXTERN int asnOpenWriteFile (char *fn)
Open an ASN.1 file for writing.
EXTERN int asnRead (byte *buffer, uint length)
Read some data from the ASN.1 file.
EXTERN int asnReadBoolean (byte *value, long length)
Read only the boolean value w/o the tag and length.
EXTERN int asnReadBooleanL (byte *value)
Read a boolean value including the length from an ASN.1-File.
EXTERN int asnReadBooleanTL (byte *value)
Read a boolean value from an ASN.1-File (with tag and length)
EXTERN int asnReadEnum (long *value, int length)
Read only the enumeration value w/o the tag and length.
EXTERN int asnReadEnumL (long *value)
Read an enumeration value including the length from an ASN.1-File.
EXTERN int asnReadEnumTL (long *value)
Read an enumeration value from an ASN.1-File (with tag and length)
EXTERN int asnReadIA5 (char *value, int len, int maxlen)
Read only the IA5-String w/o the tag and length.
EXTERN int asnReadIA5L (char *value, int maxlen)
Read an IA5-String including the length from an ASN.1-File.
EXTERN int asnReadIA5TL (char *value, int maxlen)
Read an IA5-String from the opened ASN.1 file (with tag and length)
EXTERN int asnReadInteger (long *value, int length)
Read only a integer value w/o the tag and length.
EXTERN int asnReadIntegerL (long *value)
Read an integer value including the length from an ASN.1-File.
EXTERN int asnReadIntegerTL (long *value)
Read an integer value from an ASN.1-File (with tag and length)
EXTERN int asnReadLength (long *length)
Read a "length" field from the opened ASN.1 file.
EXTERN int asnReadNullL (void)
Read a Null value with length field.
EXTERN int asnReadNullTL (void)
Read a Null value with tag and length.
EXTERN int asnReadOctet (byte *value, int length, int maxlen, byte pc)
Read an octet string from an ASN.1-File (w/o the tag and length)
EXTERN long asnReadOctetFile (int outfile, byte pc, long length)
Read an octet string from an ASN.1-File (w/o the tag and the length) and write it to another file.
EXTERN long asnReadOctetFileL (int outfile, byte pc)
Read an octet string from an ASN.1-File (with the tag) and write it to another file.
EXTERN long asnReadOctetFileTL (int outfile)
Read an octet string from an ASN.1-File and write it to another file.
EXTERN int asnReadOctetL (byte *value, int maxlen, byte pc)
Read an octet string from an ASN.1-File (with the length)
EXTERN int asnReadOctetTL (byte *value, int maxlen)
Read an octet string from an ASN.1-File (with tag and length)
EXTERN int asnReadOid (char *id, int length)
Read an object identifier from an ASN.1-File (w/o tag and length)
EXTERN int asnReadOidL (char *id)
Read an object identifier from an ASN.1-File (with length)
EXTERN int asnReadOidTL (char *id)
Read an object identifier from an ASN.1-File (with tag and length)
EXTERN int asnReadTag (byte *buffer)
Read a tag from the opened ASN.1 file.
EXTERN long asnReadTagAndLength (byte *buffer, long *length)
Read a tag and a length from the opened ASN.1 file.
EXTERN int asnSkipFile (long length)
Skip a portion of the opened ASN.1 file.
EXTERN int asnWrite (byte *buffer, uint length)
Write a buffer to the opened ASN.1 file.
EXTERN int asnWriteBoolean (byte value)
Write a boolean value into an ASN.1 file.
EXTERN int asnWriteEnum (long value)
Write an enumeration value into an ASN.1 file.
EXTERN int asnWriteIA5 (char *value)
Write an IA5-String into an ASN.1 file.
EXTERN int asnWriteInteger (long value)
Write an integer value into an ASN.1 file.
EXTERN int asnWriteLength (long length)
Write an encoded ASN.1 length field to the open ASN.1 file.
EXTERN int asnWriteNull (void)
Write a Null value into a file.
EXTERN int asnWriteOid (char *id)
Write an object identifier into an ASN.1 file.
EXTERN int asnWriteTag (byte clasS, byte pc, byte tag)
Encode and write a tag to an ASN.1 file.
EXTERN int _asnWriteOctet (byte *value, int length, byte tag)
Write an octet string into an ASN.1 file.
EXTERN int _asnWriteOctetFile (int infd, long length, byte tag)
Read data from a file and write it as an octet string into an ASN.1 file.
EXTERN long asnWriteExternalBPFile (byte *param, long parlen, char *poid, byte pet, byte pcon, int infd, char *doid, byte det, byte dcon)
Write an X.400 EXTERNAL body part to a file.
EXTERN long asnReadExternalBPFile (byte *param, long *parlen, long maxplen, char *poid, int outfd, long *datalen, char *doid, byte *dpc)
Read an X.400 EXTERNAL body part from an ASN.1 file.
Variables
int asnfd
Macro Definition Documentation
#define asnAPPLICATION 0x40
Application-Tag-Class
#define asnBOOLEAN 0x01
ASN.1 type: Boolean
Referenced by asnEncodeBoolean(), and asnReadBooleanTL().
#define asnCONSTRUCTED 0x20
Constructed coding
Referenced by asnReadOctet(), asnReadOctetFile(), and asnWriteExternalBPFile().
#define asnCONTEXT 0x80
Context-Tag-Class
Referenced by asnReadExternalBPFile(), and asnWriteExternalBPFile().
#define asnDecodeGeneralString asnDecodeOctetString
#define asnDecodeGraphicString asnDecodeOctetString
#define asnDecodeIA5String asnDecodeOctetString
#define asnDecodeNumericString asnDecodeOctetString
#define asnDecodePrintableString asnDecodeOctetString
#define asnDecodeTeletexString asnDecodeOctetString
#define asnDecodeVideotexString asnDecodeOctetString
#define asnDecodeVisibleString asnDecodeOctetString
#define asnEncodeGeneralString (v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnGENERALSTRING)
#define asnEncodeGraphicString (v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnGRAPHICSTRING)
#define asnEncodeIA5String (v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnIA5STRING)
#define asnEncodeNumericString (v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnNUMERICSTRING)
#define asnEncodePrintableString (v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnPRINTABLESTRING)
#define asnEncodeTeletexString (v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnTELETEXSTRING)
#define asnEncodeVideotexString (v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnVIDEOTEXSTRING)
#define asnEncodeVisibleString (v, l, tl, tll) asnEncodeOctetString(v,l,tl,tll,asnVISIBLESTRING)
#define asnENDCONTENTS -2l
ASN.1 length encoding end-of-contents
Referenced by asnDecodeLength(), and asnEncodeLength().
#define asnENUMERATED 0x0A
ASN.1 type: Enumerated
Referenced by asnEncodeEnum(), and asnReadEnumTL().
#define asnEXTERNAL 0x08
ASN.1 type: External
Referenced by asnReadExternalBPFile().
#define asnFALSE 0x00
ASN.1 Boolean False
Referenced by asnDecodeBoolean().
#define asnGENERALSTRING 0x1B
General String
Referenced by _asnWriteOctet(), _asnWriteOctetFile(), asnReadOctetFileTL(), and asnReadOctetTL().
#define asnGRAPHICSTRING 0x19
ASN.1 type: Graphic String
Referenced by _asnWriteOctet(), _asnWriteOctetFile(), asnReadOctetFileTL(), and asnReadOctetTL().
#define asnIA5STRING 0x16
ASN.1 type: ia5 (ASCII) -String
Referenced by _asnWriteOctet(), _asnWriteOctetFile(), asnEncodeIA5(), asnReadIA5TL(), asnReadOctetFileTL(), and asnReadOctetTL().
#define asnINDEFINITE -1l
ASN.1 length encoding indefinite
Referenced by asnDecodeLength(), asnEncodeLength(), and asnReadLength().
#define asnINTEGER 0x02
ASN.1 type: Integer
Referenced by asnEncodeInteger(), and asnReadIntegerTL().
#define asnNOTHING 0x00
ASN.1 type: No Tag
#define asnNULLVALUE 0x05
ASN.1 type: Empty, NULL-Value
Referenced by asnEncodeNull(), and asnReadNullTL().
#define asnNUMERICSTRING 0x12
ASN.1 type: Numeric String
Referenced by _asnWriteOctet(), _asnWriteOctetFile(), asnReadOctetFileTL(), and asnReadOctetTL().
#define asnOBJECTID 0x06
ASN.1 type: object identifier
Referenced by asnEncodeOid(), and asnReadOidTL().
#define asnOCTETSTRING 0x04
ASN.1 type: Byte-String
Referenced by _asnWriteOctet(), _asnWriteOctetFile(), asnReadOctetFileTL(), and asnReadOctetTL().
#define asnPRIMITIVE 0x00
Primitive coding
Referenced by _asnWriteOctetFile(), asnEncodeBoolean(), asnEncodeEnum(), asnEncodeIA5(), asnEncodeInteger(), asnEncodeNull(), and asnEncodeOctet().
#define asnPRINTABLESTRING 0x13
ASN.1 type: Printable String
Referenced by _asnWriteOctet(), _asnWriteOctetFile(), asnReadOctetFileTL(), and asnReadOctetTL().
#define asnPRIVATE 0xC0
Private-Tag-Class
#define asnReadGeneralString asnReadOctet
#define asnReadGeneralStringFile asnReadOctetFile
#define asnReadGeneralStringFileL asnReadOctetFileL
#define asnReadGeneralStringFileTL asnReadOctetFileTL
#define asnReadGeneralStringL asnReadOctetL
#define asnReadGeneralStringTL asnReadOctetTL
#define asnReadGraphicString asnReadOctet
#define asnReadGraphicStringFile asnReadOctetFile
#define asnReadGraphicStringFileL asnReadOctetFileL
#define asnReadGraphicStringFileTL asnReadOctetFileTL
#define asnReadGraphicStringL asnReadOctetL
#define asnReadGraphicStringTL asnReadOctetTL
#define asnReadIA5String asnReadOctet
#define asnReadIA5StringFile asnReadOctetFile
#define asnReadIA5StringFileL asnReadOctetFileL
#define asnReadIA5StringFileTL asnReadOctetFileTL
#define asnReadIA5StringL asnReadOctetL
#define asnReadIA5StringTL asnReadOctetTL
#define asnReadNumericString asnReadOctet
#define asnReadNumericStringFile asnReadOctetFile
#define asnReadNumericStringFileL asnReadOctetFileL
#define asnReadNumericStringFileTL asnReadOctetFileTL
#define asnReadNumericStringL asnReadOctetL
#define asnReadNumericStringTL asnReadOctetTL
#define asnReadPrintableString asnReadOctet
#define asnReadPrintableStringFile asnReadOctetFile
#define asnReadPrintableStringFileL asnReadOctetFileL
#define asnReadPrintableStringFileTL asnReadOctetFileTL
#define asnReadPrintableStringL asnReadOctetL
#define asnReadPrintableStringTL asnReadOctetTL
#define asnReadTeletexString asnReadOctet
#define asnReadTeletexStringFile asnReadOctetFile
#define asnReadTeletexStringFileL asnReadOctetFileL
#define asnReadTeletexStringFileTL asnReadOctetFileTL
#define asnReadTeletexStringL asnReadOctetL
#define asnReadTeletexStringTL asnReadOctetTL
#define asnReadVideotexString asnReadOctet
#define asnReadVideotexStringFile asnReadOctetFile
#define asnReadVideotexStringFileL asnReadOctetFileL
#define asnReadVideotexStringFileTL asnReadOctetFileTL
#define asnReadVideotexStringL asnReadOctetL
#define asnReadVideotexStringTL asnReadOctetTL
#define asnReadVisibleString asnReadOctet
#define asnReadVisibleStringFile asnReadOctetFile
#define asnReadVisibleStringFileL asnReadOctetFileL
#define asnReadVisibleStringFileTL asnReadOctetFileTL
#define asnReadVisibleStringL asnReadOctetL
#define asnReadVisibleStringTL asnReadOctetTL
#define asnSEQUENCE 0x10
ASN.1 type: Sequence, Sequence of
Referenced by asnReadExternalBPFile(), and asnWriteExternalBPFile().
#define asnSET 0x11
ASN.1 type: Set, Set of
#define asnTELETEXSTRING 0x14
ASN.1 type: Teletex
Referenced by _asnWriteOctet(), _asnWriteOctetFile(), asnReadOctetFileTL(), and asnReadOctetTL().
#define asnTRUE 0xFF
ASN.1 Boolean TRUE
Referenced by asnDecodeBoolean(), and asnEncodeBoolean().
#define asnUNIVERSAL 0x00
Universal-Tag-Class
Referenced by _asnWriteOctetFile(), asnEncodeBoolean(), asnEncodeEnum(), asnEncodeIA5(), asnEncodeInteger(), asnEncodeNull(), asnEncodeOctet(), asnReadBooleanTL(), asnReadEnumTL(), asnReadExternalBPFile(), asnReadIA5TL(), asnReadIntegerTL(), asnReadNullTL(), asnReadOctetFileTL(), asnReadOctetTL(), asnReadOidTL(), and asnWriteExternalBPFile().
#define asnVIDEOTEXSTRING 0x15
ASN.1 type: Videotex String
Referenced by _asnWriteOctet(), _asnWriteOctetFile(), asnReadOctetFileTL(), and asnReadOctetTL().
#define asnVISIBLESTRING 0x1A
ASN.1 type: Visible String
Referenced by _asnWriteOctet(), _asnWriteOctetFile(), asnReadOctetFileTL(), and asnReadOctetTL().
#define asnWriteGeneralString (v) _asnWriteOctet(v,strlen(v),asnGENERALSTRING)
#define asnWriteGeneralStringFile (f, l) _asnWriteOctetFile(f,l,asnGENERALSTRING)
#define asnWriteGraphicString (v) _asnWriteOctet(v,strlen(v),asnGRAPHICSTRING)
#define asnWriteGraphicStringFile (f, l) _asnWriteOctetFile(f,l,asnGRAPHICSTRING)
#define asnWriteIA5String (v) _asnWriteOctet(v,strlen(v),asnIA5STRING)
#define asnWriteIA5StringFile (f, l) _asnWriteOctetFile(f,l,asnIA5STRING)
#define asnWriteNumericString (v) _asnWriteOctet(v,strlen(v),asnNUMERICSTRING)
#define asnWriteNumericStringFile (f, l) _asnWriteOctetFile(f,l,asnNUMERICSTRING)
#define asnWriteOctet (v, l) _asnWriteOctet (v,l,asnOCTETSTRING)
#define asnWriteOctetFile (f, l) _asnWriteOctetFile(f,l,asnOCTETSTRING)
#define asnWritePrintableString (v) _asnWriteOctet(v,strlen(v),asnPRINTABLESTRING)
#define asnWritePrintableStringFile (f, l) _asnWriteOctetFile(f,l,asnPRINTABLESTRING)
#define asnWriteTeletexString (v) _asnWriteOctet(v,strlen(v),asnTELETEXSTRING)
#define asnWriteTeletexStringFile (f, l) _asnWriteOctetFile(f,l,asnTELETEXSTRING)
#define asnWriteVideotexString (v) _asnWriteOctet(v,strlen(v),asnVIDEOTEXSTRING)
#define asnWriteVideotexStringFile (f, l) _asnWriteOctetFile(f,l,asnVIDEOTEXSTRING)
#define asnWriteVisibleString (v) _asnWriteOctet(v,strlen(v),asnVISIBLESTRING)
#define asnWriteVisibleStringFile (f, l) _asnWriteOctetFile(f,l,asnVISIBLESTRING)
#define MAXOID 10
Maximum number of subid's in an oid
Referenced by asnEncodeOid().
Typedef Documentation
typedef unsigned char byte
typedef unsigned int uint
Function Documentation
EXTERN int _asnWriteOctet (byte * value, int length, byte tag)
Write an octet string into an ASN.1 file.
Write an octet string into an opened ASN.1 file. value is the data value to be written. length is the number of bytes to be encoded. Macros for each individual octet or other string type actually map to this function which does the writing. See akasn1.h for further details on writing of octet and other strings.
Returns
If an error occures, the function returns -1 or the number of bytes written to the file otherwise.
Note
Restriction: The length of the data has to be less than MAXINT.
See also
asnReadOctet, asnWriteOctetFile
References asnEncodeOctet(), asnGENERALSTRING, asnGRAPHICSTRING, asnIA5STRING, asnNUMERICSTRING, asnOCTETSTRING, asnPRINTABLESTRING, asnTELETEXSTRING, asnVIDEOTEXSTRING, asnVISIBLESTRING, and asnWrite().
EXTERN int _asnWriteOctetFile (int infd, long length, byte tag)
Read data from a file and write it as an octet string into an ASN.1 file.
Read data from an open file infd and write it as an octet string to an opened ASN.1 file. length is the number of bytes to encode from the original file. Macros for each individual octet or other string type actually map to this function, which does the writing. See akasn1.h for further details on writing of octet and other strings.
Returns
If an error occures, the function returns -1 or the number of bytes written to the file otherwise.
Note
Restriction: The length of the data has to be less than MAXINT.
See also
asnReadOctet, asnWriteOctetFile
References asnEncodeLength(), asnEncodeTag(), asnGENERALSTRING, asnGRAPHICSTRING, asnIA5STRING, asnNUMERICSTRING, asnOCTETSTRING, asnPRIMITIVE, asnPRINTABLESTRING, asnTELETEXSTRING, asnUNIVERSAL, asnVIDEOTEXSTRING, asnVISIBLESTRING, and asnWrite().
EXTERN void asnCloseFile (void)
Close the opened ASN.1 file.
Close the ASN.1 file which prior must have been opened by asnOpenReadFile or asnOpenWriteFile .
See also
asnOpenReadFile, asnOpenWriteFile
References asnfd.
Referenced by asnOpenReadFile(), and asnOpenWriteFile().
EXTERN int asnDecodeBoolean (byte * buffer, byte * value)
Decode a boolean value from a buffer.
This function decodes a boolean value from a buffer. buffer contains the encoded boolean value, value is the variable to fill with the result. It is assumed that buffer contains only the value, not the tag and length.
Returns
Allways return 0.
See also
asnEncodeBoolean, asnReadBoolean, asnReadBooleanTL, asnReadBooleanL, asnWriteBoolean
References asnFALSE, and asnTRUE.
Referenced by asnReadBoolean().
EXTERN int asnDecodeEnum (byte * buffer, int length, long * value)
Decode an enumeration value.
Decode an enumeration value (C-type long) from a buffer buffer. length is the length of the encoding in buffer, value is a pointer to the result variable.
Returns
This function always returns 0.
See also
asnEncodeEnum, asnReadEnum, asnWriteEnum
References asnDecodeInteger().
Referenced by asnReadEnum().
EXTERN int asnDecodeIA5 (byte * value, int length)
Decode an IA5-String.
Decode an IA5-String into an ASCII-String from the buffer value. Actually, there is nothing to do because an IA5-string is already an ASCII-String. This function exists merely for symmetry with other data types. length is the length of the encoding in value.
Returns
This function returns -1 in case of an error, or the number of characters decoded.
Note
Restriction: The length of the string has to be less than MAXINT.
See also
asnEncodeIA5, asnReadIA5, asnWriteIA5
Referenced by asnReadIA5().
EXTERN int asnDecodeInteger (byte * buffer, int length, long * value)
Decode an integer value.
Decode an integer value (C-type long) from a buffer buffer. length is the length of the encoding in buffer, value is a pointer to the result variable.
Returns
This function always returns 0.
Note
Restriction: The Integer has to be less than 2^31.
See also
asnEncodeInteger, asnReadInteger, asnWriteInteger,
Referenced by asnDecodeEnum(), and asnReadInteger().
EXTERN int asnDecodeLength (byte * buffer, long * length)
Decode a "length" field.
This function decodes a "length" field of an ASN.1 value. buffer contains the encoded length, length is a pointer to a long variable which should get the result.
Returns
The function returns the length of the encoding in buffer.
Note
Restriction: supports only length between 0 and MAXLONG.
See also
asnEncodeLength, asnReadLength, asnWriteLength
References asnENDCONTENTS, and asnINDEFINITE.
EXTERN int asnDecodeOctet (byte * value, int length)
Decode an octet string from a buffer.
Decode an octet string from a buffer. This function realy does nothing because there is not much to do at the moment. value is the pointer to the buffer which contains the data to be decoded, length is the length of the data.
Returns
If an error occures, the function returns -1, or the number of bytes decoded otherwise.
Note
The encoding has to be primitive. The constructed encoding is not supported yet. The maximum number of bytes has to be less than MAXINT.
See also
asnEncodeOctet, asnWriteOctet, asnReadOctet
Referenced by asnReadOctet().
EXTERN int asnDecodeOid (byte * buffer, int len, char * id)
Decode an object identifier from a buffer into a string.
Decode an object identifier from buffer and return it in the format "a b c ...". buffer contains the encoded object identifier. length is the length of the encoding in buffer. id is a pointer for the resulting string.
Returns
The length of the result string id is returned.
Note
Restriction: Supports only subid's less or equal 16383.
See also
asnEncodeOID, asnReadOID, asnWriteOID
Referenced by asnReadOid().
EXTERN int asnDecodeTag (byte * clasS, byte * pc, byte * tagnum, byte * buf)
Decode an ASN.1 tag.
Decode an ASN.1 tag value. class is a pointer to a variable to store the class value (asnUNIVERSAL , asnAPPLICATION , asnCONTEXT, asnPRIVATE) in. pc is a pointer to a variable to indicate wether the data following the tag is constructed or primitive (asnPRIMITIVE , asnCONSTRUCTED). tagnum is a pointer to a variable to store the tag number in. buffer is the buffer which contains the tag to decode.
Returns
If an error occures, the function returns -1, or the number of decoded bytes otherwise.
See also
asnEncodeTag, asnReadTag, asnReadTagAndLength, asnWriteTag
Referenced by asnReadBooleanTL(), asnReadEnumTL(), asnReadExternalBPFile(), asnReadIA5TL(), asnReadIntegerTL(), asnReadNullTL(), asnReadOctet(), asnReadOctetFile(), asnReadOctetFileTL(), asnReadOctetTL(), and asnReadOidTL().
EXTERN int asnEncodeBoolean (byte * buffer, byte value)
Encode a boolean value.
Encode a boolean value into a buffer. The type tag and length is also encoded.
Returns
The function returns -1 in case of an error, or the length of the encoding in the buffer.
See also
asnDecodeBoolean, asnReadBoolean, asnReadBooleanTL, asnReadBooleanL, asnWriteBoolean
References asnBOOLEAN, asnEncodeLength(), asnEncodeTag(), asnPRIMITIVE, asnTRUE, and asnUNIVERSAL.
Referenced by asnWriteBoolean().
EXTERN int asnEncodeBooleanValue (byte * buffer, byte value)
Encode a boolean value.
Encode a boolean value into a buffer. The type tag and length is NOT encoded, only the value
Returns
The function returns -1 in case of an error, or the length of the encoding in the buffer.
See also
asnDecodeBoolean, asnReadBoolean, asnReadBooleanTL, asnReadBooleanL, asnWriteBoolean
EXTERN int asnEncodeEnum (byte * buffer, long value)
Encode an enumeration value with tag and length.
Encode an enumeration (C-type long) with tag and length into a buffer. This function does the same as the function asnEncodeInteger except the encoding value of the tag. buffer is the buffer to fill with the resulting encoding, value is the enumeration value to encode.
Returns
If an error occures, the function returns -1, or the length of the result in buffer otherwise.
See also
asnDecodeEnum, asnReadEnum, asnWriteEnum
Note
Restriction: The Integer has to be less than 2^31.
References asnEncodeLength(), asnEncodeTag(), asnENUMERATED, asnPRIMITIVE, asnUNIVERSAL, FF_VALUE, IGNORE_VALUE, and NULL_VALUE.
Referenced by asnWriteEnum().
EXTERN int asnEncodeEnumValue (byte * buffer, long value)
Encode an enumeration value as an integer with tag and length.
Encode an enumeration (C-type long) with tag and length into a buffer. This function does the same as the function asnEncodeIntegerValue except the encoding value of the tag. buffer is the buffer to fill with the resulting encoding, value is the enumeration value to encode.
Returns
If an error occures, the function returns -1, or the length of the result in buffer otherwise.
See also
asnDecodeEnum, asnReadEnum, asnWriteEnum
References asnEncodeIntegerValue().
EXTERN int asnEncodeIA5 (char * value, byte * buffer, int * length)
Encode an IA5-String with tag and length.
Encode an IA5-String with tag and length into a buffer. value is a 0-terminated C-string. buffer is a buffer in which the encoding of the tag and the length will be done. The length of the encoding in buffer will be returned in length.
Returns
If an error occures, the function returns -1, -2 of the value is not a legal IA5-String or the length of the result in buffer otherwise.
Note
Restriction: The length of the string has to be less than MAXINT.
See also
asnDecodeIA5, asnReadIA5, asnWriteIA5
References asnEncodeLength(), asnEncodeTag(), asnIA5STRING, asnPRIMITIVE, and asnUNIVERSAL.
Referenced by asnWriteIA5().
EXTERN int asnEncodeInteger (byte * buffer, long value)
Encode an integer value with tag and length.
Encode an Integer (C-type long) with tag and length into a buffer. buffer is the buffer to fill with the resulting encoding, value is the integer value to encode.
Returns
If an error occures, the function returns -1, or the length of the result in buffer otherwise.
Note
Restriction: The Integer has to be less than 2^31.
See also
asnDecodeInteger, asnReadInteger, asnWriteInteger
References asnEncodeTag(), asnINTEGER, asnPRIMITIVE, and asnUNIVERSAL.
Referenced by asnWriteInteger().
EXTERN int asnEncodeIntegerValue (byte * buffer, long value)
Encode an integer value with tag (no length!)
Encode an Integer (C-type long) with tag but without the length into a buffer. buffer is the buffer to fill with the resulting encoding, value is the integer value to encode.
Returns
If an error occures, the function returns -1, or the length of the result in buffer otherwise.
Note
Restriction: The Integer has to be less than 2^31.
See also
asnDecodeInteger, asnReadInteger, asnWriteInteger
Referenced by asnEncodeEnumValue().
EXTERN int asnEncodeLength (byte * buffer, long length)
Encode a "length" field.
Encode a length field length into the buffer.
Returns
If an error occures, the function returns -1, or the length of the encoding in buffer otherwise.
Note
Restriction: supports only length between 0 and MAXLONG.
See also
asnDecodeLength, asnReadLength, asnWriteLength
References asnENDCONTENTS, and asnINDEFINITE.
Referenced by _asnWriteOctetFile(), asnEncodeBoolean(), asnEncodeEnum(), asnEncodeIA5(), asnEncodeOctet(), asnWriteExternalBPFile(), and asnWriteLength().
EXTERN int asnEncodeNull (byte * value)
Encode a Null value.
Encode a Null value. That is just the tag and the length field, no value. value is the buffer to be filled.
Returns
If an error occures, the function returns -1, or the length of the encoding in value otherwise.
See also
asnReadNullL, asnReadNullTL, asnWriteNull
References asnEncodeTag(), asnNULLVALUE, asnPRIMITIVE, and asnUNIVERSAL.
Referenced by asnWriteNull().
EXTERN int asnEncodeOctet (byte * value, int length, byte * tag_len, int * tl_length, byte tag)
Encode an octet string with tag and length into a buffer.
Encode an octet string with tag and length into a buffer. value is a pointer to the buffer to encode. length is the number of bytes in the value buffer to encode. tag_len is the buffer for the tag and the length of the encoding. tl_length is a pointer to a variable for the resulting length of tag_len.
Returns
If an error occures, the function returns -1, or the length of the encoding (only the octet string, w/o tl_length) otherwise.
Note
The encoding has to be ASN.1 primitive. The constructed encoding is not supported yet. The maximum number of bytes has to be less than MAXINT.
See also
asnFtell, asnOpenReadFile, asnOpenQriteFile
References asnEncodeLength(), asnEncodeTag(), asnPRIMITIVE, and asnUNIVERSAL.
Referenced by _asnWriteOctet().
EXTERN int asnEncodeOid (byte * buffer, char * id)
Encode an object identifier with the tag and length.
Encode an object identifier from a string id into the buffer buffer including the tag and the length. The format of the input must be "a b c ...".
Returns
The length of the encoding in buffer.
Note
Restriction: The maximum length has to be less or equal 127 octets and the maximum number of subidentifiers is 10. The number of oid's has to be equal or greater than 2.Supports only subid's less or equal 16383.
See also
asnDecodeOID, asnReadOID, asnWriteOID
References asnOBJECTID, and MAXOID.
Referenced by asnWriteOid().
EXTERN int asnEncodeTag (byte * buf, byte clasS, byte pc, byte tag)
Encode an ASN.1 tag.
Encode an ASN.1 tag value. class is the class of the tag (asnUNIVERSAL , asnAPPLICATION , asnCONTEXT , asnPRIVATE). pc is a flag to indicate wether the data following the tag is constructed or primitive (asnPRIMITIVE , asnCONSTRUCTED). tag is the number of the tag. buffer is the buffer which will get the resulting encoding.
Returns
If an error occures, the function returns -1, or the number of encoded bytes otherwise.
See also
asnDecodeTag, asnReadTag, asnReadTagAndLength, asnWriteTag
Referenced by _asnWriteOctetFile(), asnEncodeBoolean(), asnEncodeEnum(), asnEncodeIA5(), asnEncodeInteger(), asnEncodeNull(), asnEncodeOctet(), asnWriteExternalBPFile(), and asnWriteTag().
EXTERN int asnFseek (long pos)
Seek to a position pos in the open ASN.1-file.
Returns
If an error occures, the function returns -1, or 0 otherwise.
See also
asnFtell, asnOpenReadFile, asnOpenWriteFile
References asnfd.
Referenced by asnIsEOC().
EXTERN long asnFtell (void)
Get position in the opened ASN.1-File.
This function returns the current position of the internal file descriptor in the opened ASN.1 file.
Returns
If an error occures, the function returns -1, or a value equal or greater than 0 (the position).
See also
asnFseek, asnOpenReadFile, asnOpenWriteFile
References asnfd.
Referenced by asnIsEOC().
EXTERN int asnIsEOC (void)
Check for End-Of-Contents in the opened ASN.1 file.
This function provides a way to check whether the next token in the opened ASN.1 file is an End-Of-Contents token EOC.
Returns
If an EOC token is the next in the file, 1 is returned, 0 otherwise.
See also
asnFtell, asnFseek, asnOpenReadFile, asnOpenWriteFile
References asnFseek(), asnFtell(), and asnRead().
EXTERN int asnOpenReadFile (char * fn)
Open an ASN.1 file for reading.
Open an ASN.1 file for reading. fn is the file name of the file.
Returns
If an error occures, the function returns -1, or the internal file descriptor asnfd otherwise.
See also
asnOpenWriteFile, asnCloseFile, asnRead
References asnCloseFile(), and asnfd.
EXTERN int asnOpenWriteFile (char * fn)
Open an ASN.1 file for writing.
Open an ASN.1 file for writing. fn is the file name of the file.
Returns
If an error occures, the function returns -1, or the internal file descriptor asnfd otherwise.
See also
asnOpenWriteFile, asnCloseFile, asnWrite
References asnCloseFile(), and asnfd.
EXTERN int asnRead (byte * buffer, uint length)
Read some data from the ASN.1 file.
Read some data from the opened ASN.1 file. buffer is the buffer to be filled with the data, length is the number of bytes to be read.
Returns
If an error occures, the function returns -1, 0 at EOF, or the number of bytes read otherwise.
See also
asnOpenReadFile, asnWrite
References asnfd.
Referenced by asnIsEOC(), asnReadBoolean(), asnReadEnum(), asnReadExternalBPFile(), asnReadIA5(), asnReadInteger(), asnReadLength(), asnReadOctet(), asnReadOid(), and asnReadTag().
EXTERN int asnReadBoolean (byte * value, long length)
Read only the boolean value w/o the tag and length.
Read only the boolean value from the opened ASN.1 file, without the tag and the length. These had to be read prior. value is a pointer to the buffer to encode the value in. length is the number of bytes to read from the file.
Returns
If an error occures, the function returns -1, or 0 otherwise.
See also
asnDecodeBoolean, asnReadBooleanL, asnReadBooleanTL
References asnDecodeBoolean(), and asnRead().
Referenced by asnReadBooleanL().
EXTERN int asnReadBooleanL (byte * value)
Read a boolean value including the length from an ASN.1-File.
Read a boolean value from the opened ASN.1 file, including the length. The type tag may have been read prior. value is the variable to fill with the result.
Returns
If an error occures, the function returns -1, or 0 otherwise.
See also
asnDecodeBoolean, asnReadBoolean, asnReadBooleanTL
References asnReadBoolean(), and asnReadLength().
Referenced by asnReadBooleanTL().
EXTERN int asnReadBooleanTL (byte * value)
Read a boolean value from an ASN.1-File (with tag and length)
Read a boolean value from the opened ASN.1 file, including the tag and the length of the encoding. value is the variable to fill with the result.
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not of type boolean. 0 is return if no error occured.
See also
asnDecodeBoolean, asnReadBoolean, asnReadBooleanL
References asnBOOLEAN, asnDecodeTag(), asnReadBooleanL(), asnReadTag(), asnSkipFile(), and asnUNIVERSAL.
EXTERN int asnReadEnum (long * value, int length)
Read only the enumeration value w/o the tag and length.
Read only the enumeration value from the opened ASN.1 file, without the tag and the length. These had to be read prior. value is a pointer to the buffer to encode the value in. length is the number of bytes to read from the file.
Returns
If an error occures, the function returns -1, or the length of the encoded enumeration value otherwise.
See also
asnDecodeEnum, asnEncodeEnum, asnWriteEnum, asnReadEnumL, asnReadEnumTL
References asnDecodeEnum(), and asnRead().
Referenced by asnReadEnumL().
EXTERN int asnReadEnumL (long * value)
Read an enumeration value including the length from an ASN.1-File.
Read an enumeration value from the opened ASN.1 file, including the length. The type tag may have been read prior. value is the variable to fill with the result.
Returns
If an error occures, the function returns -1, or 0 otherwise.
See also
asnDecodeEnum, asnEncodeEnum, asnWriteEnum, asnReadEnum, sasnReadEnumTL
References asnReadEnum(), and asnReadLength().
Referenced by asnReadEnumTL().
EXTERN int asnReadEnumTL (long * value)
Read an enumeration value from an ASN.1-File (with tag and length)
Read an enumeration value from the opened ASN.1 file, including the tag and the length of the encoding. value is the variable to fill with the result.
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not of type enumeration. 0 is return if no error occured.
See also
asnDecodeEnum, asnEncodeEnum, asnWriteEnum, asnReadEnumL
References asnDecodeTag(), asnENUMERATED, asnReadEnumL(), asnReadTag(), asnSkipFile(), and asnUNIVERSAL.
EXTERN long asnReadExternalBPFile (byte * param, long * parlen, long maxplen, char * poid, int outfd, long * datalen, char * doid, byte * dpc)
Read an X.400 EXTERNAL body part from an ASN.1 file.
Read an X.400 EXTERNAL body part from an ASN.1 file. Only direct-reference (oid) and encoding (0, 1, 2) are supported.
Returns
If an error occures, the function returns -1, or the number of bytes read otherwise.
See also
asnWriteExternalBPFile
References asnCONTEXT, asnDecodeTag(), asnEXTERNAL, asnfd, asnRead(), asnReadOid(), asnReadTagAndLength(), asnSEQUENCE, asnSkipFile(), and asnUNIVERSAL.
EXTERN int asnReadIA5 (char * value, int length, int maxlen)
Read only the IA5-String w/o the tag and length.
Read only the IA5-String from the opened ASN.1 file, without the tag and the length. These had to be read prior. value is a pointer to the buffer to encode the string in. length is the number of bytes to read from the file. maxlen is maximum number of characters to be read.
Returns
If an error occures, the function returns -1. Otherwise, the number of characters read is returned.
Note
Restriction: The length of the string has to be less than MAXINT.
See also
asnDecodeIA5, asnEncodeIA5, asnWriteIA5, asnReadIA5L, asnReadIA5TL
References asnDecodeIA5(), asnRead(), and asnSkipFile().
Referenced by asnReadIA5L().
EXTERN int asnReadIA5L (char * value, int maxlen)
Read an IA5-String including the length from an ASN.1-File.
Read an IA5-String from the opened ASN.1 file, including the length. The type tag may have been read prior. value is the variable to fill with the result. maxlen is maximum number of characters to be read.
Returns
If an error occures, the function returns -1. Otherwise, the number of characters read is returned.
Note
Restriction: The length of the string has to be less than MAXINT.
See also
asnDecodeIA5, asnEncodeIA5, asnWriteIA5, asnReadIA5, asnReadIA5TL
References asnReadIA5(), and asnReadLength().
Referenced by asnReadIA5TL().
EXTERN int asnReadIA5TL (char * value, int maxlen)
Read an IA5-String from the opened ASN.1 file (with tag and length)
Read an IA5-String from the opened ASN.1 file, including the tag and the length of the encoding. value is the variable to fill with the result, maxlen is the maximum number of characters to be read (mostly the size of value).
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not of type IA5-String. Otherwise, the number of characters read is returned.
Note
Restriction: The length of the string has to be less than MAXINT.
See also
asnDecodeIA5, asnEncodeIA5, asnWriteIA5, asnReadIA5L
References asnDecodeTag(), asnIA5STRING, asnReadIA5L(), asnReadTag(), asnSkipFile(), and asnUNIVERSAL.
EXTERN int asnReadInteger (long * value, int length)
Read only a integer value w/o the tag and length.
Read only an ineteger value from the opened ASN.1 file, without the tag and the length. These had to be read prior. value is a pointer to the buffer to encode the value in. length is the number of bytes to read from the file.
Returns
If an error occures, the function returns -1, or the length of the encoded integer value otherwise.
Note
Restriction: The Integer has to be less than 2^31.
See also
asnDecodeInteger, asnEncodeInteger, asnWriteInteger, asnReadIntegerL, asnReadIntegerTL
References asnDecodeInteger(), and asnRead().
Referenced by asnReadIntegerL().
EXTERN int asnReadIntegerL (long * value)
Read an integer value including the length from an ASN.1-File.
Read an integer value from the opened ASN.1 file, including the length. The type tag must have been read prior. value is the variable to fill with the result.
Returns
If an error occures, the function returns -1, or 0 otherwise.
Note
Restriction: The Integer has to be less than 2^31.
See also
asnDecodeInteger, asnEncodeInteger, asnWriteInteger, asnReadInteger, asnReadIntegerTL
References asnReadInteger(), and asnReadLength().
Referenced by asnReadIntegerTL().
EXTERN int asnReadIntegerTL (long * value)
Read an integer value from an ASN.1-File (with tag and length)
Read an integer value from the opened ASN.1 file, including the tag and the length of the encoding. value is the variable to fill with the result.
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not of type integer. 0 is return if no error occured.
Note
Restriction: The Integer has to be less than 2^31.
See also
asnDecodeInteger, asnEncodeInteger, asnWriteInteger, asnReadIntegerL
References asnDecodeTag(), asnINTEGER, asnReadIntegerL(), asnReadTag(), asnSkipFile(), and asnUNIVERSAL.
EXTERN int asnReadLength (long * length)
Read a "length" field from the opened ASN.1 file.
This function reads the ASN.1 length field from an opened file. length is a pointer to a long variable which will get the result.
Returns
If an error occures, the function returns -1, or the length of the encoding read from the file otherwise.
Note
Restriction: supports only length between 0 and MAXLONG.
See also
asnOpenReadFile, asnOpenWriteFile, asnEncodeLength, asnDecodeLength, asnWriteLength
References asnINDEFINITE, and asnRead().
Referenced by asnReadBooleanL(), asnReadEnumL(), asnReadIA5L(), asnReadIntegerL(), asnReadOctet(), asnReadOctetFile(), asnReadOctetFileL(), asnReadOctetL(), asnReadOidL(), and asnReadTagAndLength().
EXTERN int asnReadNullL (void)
Read a Null value with length field.
Read a Null-value (with length) from the opened ASN.1 file without the tag. This function does nothing more than read one byte of the input stream and ignore the length-field which should be 0.
Returns
If an error occures, the function returns -1, or the number of bytes read otherwise.
See also
asnEncodeNull, asnReadNullTL, asnWriteNull
References asnSkipFile().
Referenced by asnReadNullTL().
EXTERN int asnReadNullTL (void)
Read a Null value with tag and length.
Read a Null value from an opened ASN.1 file, including the tag and the length.
Returns
If an error occures, the function returns -1, -2 if the value read is not a Null value or the number of bytes read otherwise.
See also
asnEncodeNull, asnReadNullL, asnWriteNull
References asnDecodeTag(), asnNULLVALUE, asnReadNullL(), asnReadTag(), asnSkipFile(), and asnUNIVERSAL.
EXTERN int asnReadOctet (byte * value, int length, int maxlen, byte pc)
Read an octet string from an ASN.1-File (w/o the tag and length)
Read an octet string from the opened ASN.1 file (only the data). The tag and the length must have been read prior to the call of this function. value is the variable to fill with the result. length is the length of the data to be read. maxlen is the maximum number of bytes to be read. pc is a flag whether the encoding is primitive (asnPRIMITIVE) or constructed (asnCONSTRUCTED).
Returns
If an error occures, the function returns -1. Otherwise, the number of bytes read is returned.
Note
The maximum number of bytes has to be less than MAXINT.
See also
asnDecodeOctet, asnEncodeOctet, asnWriteOctet, asnReadOctetTL, asnReadOctetFileTL
References asnCONSTRUCTED, asnDecodeOctet(), asnDecodeTag(), asnRead(), asnReadLength(), asnReadOctet(), asnReadTag(), and asnSkipFile().
Referenced by asnReadOctet(), and asnReadOctetL().
EXTERN long asnReadOctetFile (int outfile, byte pc, long length)
Read an octet string from an ASN.1-File (w/o the tag and the length) and write it to another file.
Read an octet string from the opened ASN.1 file (without the tag and the length) and write it to another open file outfile. pc is a flag whether the encoding is primitive (asnPRIMITIVE) or constructed (asnCONSTRUCTED). length is the number of bytes to be read.
Returns
If an error occures, the function returns -1. Otherwise, the number of bytes read is returned.
Note
The maximum number of bytes has to be less than MAXINT.
See also
asnDecodeOctet, asnEncodeOctet, asnWriteOctet, asnReadOctetTL, asnReadOctetFile
References asnCONSTRUCTED, asnDecodeTag(), asnfd, asnReadLength(), asnReadOctetFile(), and asnReadTag().
Referenced by asnReadOctetFile(), and asnReadOctetFileL().
EXTERN long asnReadOctetFileL (int outfile, byte pc)
Read an octet string from an ASN.1-File (with the tag) and write it to another file.
Read an octet string from the opened ASN.1 file (and the length) and write it to another open file outfile. pc is a flag whether the encoding is primitive (asnPRIMITIVE) or constructed (asnCONSTRUCTED).
Returns
If an error occures, the function returns -1. Otherwise, the number of bytes read is returned.
Note
The maximum number of bytes has to be less than MAXINT.
See also
asnDecodeOctet, asnEncodeOctet, asnWriteOctet, asnReadOctetTL, asnReadOctetFile
References asnReadLength(), and asnReadOctetFile().
Referenced by asnReadOctetFileTL().
EXTERN long asnReadOctetFileTL (int outfile)
Read an octet string from an ASN.1-File and write it to another file.
Read an octet string from the opened ASN.1 file (including the tag and the length) and write it to another open file outfile.
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not an octet string. Otherwise, the number of bytes read is returned.
Note
The maximum number of bytes has to be less than MAXINT.
See also
asnDecodeOctet, asnEncodeOctet, asnWriteOctet, asnReadOctetTL, asnReadOctetFile
References asnDecodeTag(), asnGENERALSTRING, asnGRAPHICSTRING, asnIA5STRING, asnNUMERICSTRING, asnOCTETSTRING, asnPRINTABLESTRING, asnReadOctetFileL(), asnReadTag(), asnSkipFile(), asnTELETEXSTRING, asnUNIVERSAL, asnVIDEOTEXSTRING, and asnVISIBLESTRING.
EXTERN int asnReadOctetL (byte * value, int maxlen, byte pc)
Read an octet string from an ASN.1-File (with the length)
Read an octet string from the opened ASN.1 file, including the length of the encoding. The tag must have been read prior to the call of this function. value is the variable to fill with the result. maxlen is the maximum number of bytes to be read. pc is a flag whether the encoding is primitive (asnPRIMITIVE) or constructed (asnCONSTRUCTED).
Returns
If an error occures, the function returns -1. Otherwise, the number of bytes read is returned.
Note
The maximum number of bytes has to be less than MAXINT.
See also
asnDecodeOctet, asnEncodeOctet, asnWriteOctet, asnReadOctet, asnReadOctetFileTL
References asnReadLength(), and asnReadOctet().
Referenced by asnReadOctetTL().
EXTERN int asnReadOctetTL (byte * value, int maxlen)
Read an octet string from an ASN.1-File (with tag and length)
Read an octet string from the opened ASN.1 file, including the tag and the length of the encoding. value is the variable to fill with the result. maxlen is the maximum number of bytes to be read.
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not an octet string. Otherwise, the number of bytes read is returned.
Note
The maximum number of bytes has to be less than MAXINT.
See also
asnDecodeOctet, asnEncodeOctet, asnWriteOctet, asnReadOctetL, asnReadOctetFileTL
References asnDecodeTag(), asnGENERALSTRING, asnGRAPHICSTRING, asnIA5STRING, asnNUMERICSTRING, asnOCTETSTRING, asnPRINTABLESTRING, asnReadOctetL(), asnReadTag(), asnSkipFile(), asnTELETEXSTRING, asnUNIVERSAL, asnVIDEOTEXSTRING, and asnVISIBLESTRING.
EXTERN int asnReadOid (char * id, int length)
Read an object identifier from an ASN.1-File (w/o tag and length)
Read an object identifier from the opened ASN.1 file. length is the number of bytes to be read. id is the variable to fill with the result.
Returns
If an error occures, the function returns -1. Otherwise, the length of the resulting object identifier string is returned.
Note
Restriction: The maximum length has to be less or equal 127 octets and the maximum number of subidentifiers is 10. The number of oid's has to be equal or greater than 2. Supports only subid's less or equal 16383.
See also
asnDecodeOID, asnEncodeOID, asnReadOIDTL, asnWriteOID
References asnDecodeOid(), and asnRead().
Referenced by asnReadExternalBPFile(), and asnReadOidL().
EXTERN int asnReadOidL (char * id)
Read an object identifier from an ASN.1-File (with length)
Read an object identifier from the opened ASN.1 file, including the length of the encoding. id is the variable to fill with the result.
Returns
If an error occures, the function returns -1. Otherwise, the length of the resulting object identifier string is returned.
Note
Restriction: The maximum length has to be less or equal 127 octets and the maximum number of subidentifiers is 10. The number of oid's has to be equal or greater than 2. Supports only subid's less or equal 16383.
See also
asnDecodeOID, asnEncodeOID, asnReadOID, asnWriteOID
References asnReadLength(), and asnReadOid().
Referenced by asnReadOidTL().
EXTERN int asnReadOidTL (char * id)
Read an object identifier from an ASN.1-File (with tag and length)
Read an object identifier from the opened ASN.1 file, including the tag and the length of the encoding. id is the variable to fill with the result.
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not an object identifier. Otherwise, the length of the resulting object identifier string is returned.
Note
Restriction: The maximum length has to be less or equal 127 octets and the maximum number of subidentifiers is 10. The number of oid's has to be equal or greater than 2. Supports only subid's less or equal 16383.
See also
asnDecodeOID, asnEncodeOID, asnReadOIDL, asnWriteOID
References asnDecodeTag(), asnOBJECTID, asnReadOidL(), asnReadTag(), asnSkipFile(), and asnUNIVERSAL.
EXTERN int asnReadTag (byte * buffer)
Read a tag from the opened ASN.1 file.
Read a tag from the opened ASN.1 file. buffer is a pointer to the buffer which will get the resulting tag encoding.
Returns
If an error occures, the function returns -1, or the size of the tag in buffer otherwise.
See also
asnOpenReadFile, asnRead, asnDecodeTag
References asnRead().
Referenced by asnReadBooleanTL(), asnReadEnumTL(), asnReadIA5TL(), asnReadIntegerTL(), asnReadNullTL(), asnReadOctet(), asnReadOctetFile(), asnReadOctetFileTL(), asnReadOctetTL(), asnReadOidTL(), and asnReadTagAndLength().
EXTERN long asnReadTagAndLength (byte * buffer, long * length)
Read a tag and a length from the opened ASN.1 file.
Read a tag and a length from the opened ASN.1 file. buffer is a pointer to the buffer for the read tag. length is a pointer to a variable, which will get the decoded length.
Returns
If an error occures, the function returns -1, or 0 otherwise.
See also
asnReadTag, asnReadLength
References asnReadLength(), and asnReadTag().
Referenced by asnReadExternalBPFile().
EXTERN int asnSkipFile (long length)
Skip a portion of the opened ASN.1 file.
This function skips length bytes of the data in the opened ASN.1 file.
Returns
If an error occures, the function returns -1, or 0 otherwise.
See also
asnFtell, asnFSeek, asnOpenReadFile, asnOpenWriteFile
References asnfd.
Referenced by asnReadBooleanTL(), asnReadEnumTL(), asnReadExternalBPFile(), asnReadIA5(), asnReadIA5TL(), asnReadIntegerTL(), asnReadNullL(), asnReadNullTL(), asnReadOctet(), asnReadOctetFileTL(), asnReadOctetTL(), and asnReadOidTL().
EXTERN int asnWrite (byte * buffer, uint len)
Write a buffer to the opened ASN.1 file.
Write a length bytes of the buffer buffer to the opened ASN.1 file.
Returns
If an error occures, the function returns -1, or the number of bytes written otherwise.
See also
asnOpenReadFile, asnOpenWriteFile
References asnfd.
Referenced by _asnWriteOctet(), _asnWriteOctetFile(), asnWriteBoolean(), asnWriteEnum(), asnWriteExternalBPFile(), asnWriteIA5(), asnWriteInteger(), asnWriteLength(), asnWriteNull(), asnWriteOid(), and asnWriteTag().
EXTERN int asnWriteBoolean (byte value)
Write a boolean value into an ASN.1 file.
Write a boolean value into an opened ASN.1 file. value is the boolean value to be encoded. It must be either asnFALSE or asnTRUE .
Returns
If an error occures, the function returns -1, or 0 otherwise.
See also
asnReadBoolean
References asnEncodeBoolean(), and asnWrite().
EXTERN int asnWriteEnum (long value)
Write an enumeration value into an ASN.1 file.
Write an enumeration value into an opened ASN.1 file. value is the enum value to be encoded.
Returns
If an error occures, the function returns -1, or the number of bytes written to the file otherwise.
See also
asnReadEnum
References asnEncodeEnum(), and asnWrite().
EXTERN long asnWriteExternalBPFile (byte * param, long parlen, char * poid, byte pet, byte pcon, int infd, char * doid, byte det, byte dcon)
Write an X.400 EXTERNAL body part to a file.
Write an X.400 EXTERNAL body part to a file. Only direct-reference (oid) and encoding (0, 1, 2) are supported. param is a pointer to the encoded (!) parameter part or 0. parlen is the length of the data in param or 0. poid is the OID of the parameter part or 0. pet is the type for the CHOICE-Tag (0,1,2) of the parameter part. pcon is a flag whether the parameters are constructed or not. infd is the File descriptor to the (encoded) data. doid is the OID of the data part. det is the type for the CHOICE-Tag (0,1,2) of the data part. dcon is a flag whether the parameters are constructed or primitive.
Returns
If an error occures, the function returns -1, or the length of theencoding otherwise.
See also
asnReadExternalBPFile
References asnCONSTRUCTED, asnCONTEXT, asnEncodeLength(), asnEncodeTag(), asnSEQUENCE, asnUNIVERSAL, and asnWrite().
EXTERN int asnWriteIA5 (char * value)
Write an IA5-String into an ASN.1 file.
Write an IA5-String into an opened ASN.1 file. value is the string value to be written.
Returns
If an error occures, the function returns -1, -2 if value does not contain a legal IA5-String or the number of bytes written to the file otherwise.
See also
asnReadIA5
References asnEncodeIA5(), and asnWrite().
EXTERN int asnWriteInteger (long value)
Write an integer value into an ASN.1 file.
Write an integer value into an opened ASN.1 file. value is the integer value to be encoded.
Returns
If an error occures, the function returns -1, or the number of bytes written to the file otherwise.
See also
asnReadInteger
References asnEncodeInteger(), and asnWrite().
EXTERN int asnWriteLength (long length)
Write an encoded ASN.1 length field to the open ASN.1 file.
Encode and write an ASN.1 length field to the opened ASN.1 file. length is the length to be encoded.
Returns
If an error occures, the function returns -1, or the length of the encoding otherwise.
Note
Restriction: supports only length between 0 and MAXLONG.
See also
asnOpenReadFile, asnOpenWriteFile, asnEncodeLength, asnDecodeLength, asnReadLength
References asnEncodeLength(), and asnWrite().
EXTERN int asnWriteNull (void)
Write a Null value into a file.
Write a Null value into the opened ASN.1 file.
Returns
If an error occures, the function returns -1, or the number of bytes written otherwise.
See also
asnEncodeNull, asnReadNullTL, asnReadNullL
References asnEncodeNull(), and asnWrite().
EXTERN int asnWriteOid (char * id)
Write an object identifier into an ASN.1 file.
Write an object identifier into an opened ASN.1 file. id is the enum value to be encoded. The format of the input must be "a b c ...".
Returns
If an error occures, the function returns -1, or the number of bytes written to the file otherwise.
Note
Restriction: Supports only subid's less or equal 16383.
See also
asnReadOID, asnEncodeOID
References asnEncodeOid(), and asnWrite().
EXTERN int asnWriteTag (byte clasS, byte pc, byte tag)
Encode and write a tag to an ASN.1 file.
Encode and write a tag to the opened ASN.1 file. clasS is the class of the tag (asnUNIVERSAL , asnAPPLICATION , asnCONTEXT , asnPRIVATE). pc is a flag to indicate wether the data following the tag is constructed or primitive (asnPRIMITIVE , asnCONSTRUCTED). tag is the number of the tag.
Returns
If an error occures, the function returns -1, or the size of the encoded tag otherwise.
See also
asnWrite, asnEncodeTag
References asnEncodeTag(), and asnWrite().
Variable Documentation
int asnfd
Globally used file descriptor.
Filedescriptor for the ASN.1-file
Referenced by asnCloseFile(), asnFseek(), asnFtell(), asnOpenReadFile(), asnOpenWriteFile(), asnRead(), asnReadExternalBPFile(), asnReadOctetFile(), asnSkipFile(), and asnWrite().