AKASN.1: src/boolrd.c File Reference
boolrd.c File Reference
#include "akasn1.h"
Functions
int asnReadBooleanTL (byte *value)
Read a boolean value from an ASN.1-File (with tag and length)
int asnReadBooleanL (byte *value)
Read a boolean value including the length from an ASN.1-File.
int asnReadBoolean (byte *value, long length)
Read only the boolean value w/o the tag and length.
Function Documentation
int asnReadBoolean (byte * value, long length)
Read only the boolean value w/o the tag and length.
Read only the boolean value from the opened ASN.1 file, without the tag and the length. These had to be read prior. value is a pointer to the buffer to encode the value in. length is the number of bytes to read from the file.
Returns
If an error occures, the function returns -1, or 0 otherwise.
See also
asnDecodeBoolean, asnReadBooleanL, asnReadBooleanTL
References asnDecodeBoolean(), and asnRead().
Referenced by asnReadBooleanL().
int asnReadBooleanL (byte * value)
Read a boolean value including the length from an ASN.1-File.
Read a boolean value from the opened ASN.1 file, including the length. The type tag may have been read prior. value is the variable to fill with the result.
Returns
If an error occures, the function returns -1, or 0 otherwise.
See also
asnDecodeBoolean, asnReadBoolean, asnReadBooleanTL
References asnReadBoolean(), and asnReadLength().
Referenced by asnReadBooleanTL().
int asnReadBooleanTL (byte * value)
Read a boolean value from an ASN.1-File (with tag and length)
Read a boolean value from the opened ASN.1 file, including the tag and the length of the encoding. value is the variable to fill with the result.
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not of type boolean. 0 is return if no error occured.
See also
asnDecodeBoolean, asnReadBoolean, asnReadBooleanL
References asnBOOLEAN, asnDecodeTag(), asnReadBooleanL(), asnReadTag(), asnSkipFile(), and asnUNIVERSAL.