AKASN.1: src/boolenc.c File Reference
boolenc.c File Reference
#include "akasn1.h"
Functions
int asnEncodeBoolean (byte *buffer, byte value)
Encode a boolean value.
int asnEncodeBooleanValue (byte *buffer, byte value)
Encode a boolean value.
Function Documentation
int asnEncodeBoolean (byte * buffer, byte value)
Encode a boolean value.
Encode a boolean value into a buffer. The type tag and length is also encoded.
Returns
The function returns -1 in case of an error, or the length of the encoding in the buffer.
See also
asnDecodeBoolean, asnReadBoolean, asnReadBooleanTL, asnReadBooleanL, asnWriteBoolean
References asnBOOLEAN, asnEncodeLength(), asnEncodeTag(), asnPRIMITIVE, asnTRUE, and asnUNIVERSAL.
Referenced by asnWriteBoolean().
int asnEncodeBooleanValue (byte * buffer, byte value)
Encode a boolean value.
Encode a boolean value into a buffer. The type tag and length is NOT encoded, only the value
Returns
The function returns -1 in case of an error, or the length of the encoding in the buffer.
See also
asnDecodeBoolean, asnReadBoolean, asnReadBooleanTL, asnReadBooleanL, asnWriteBoolean