AKASN.1: src/enumenc.c File Reference
enumenc.c File Reference
#include "akasn1.h"
Macros
#define IGNORE_VALUE 0
#define NULL_VALUE 1
#define FF_VALUE 2
Functions
int asnEncodeEnum (byte *buffer, long value)
Encode an enumeration value with tag and length.
int asnEncodeEnumValue (byte *buffer, long value)
Encode an enumeration value as an integer with tag and length.
Macro Definition Documentation
#define FF_VALUE 2
Referenced by asnEncodeEnum().
#define IGNORE_VALUE 0
Referenced by asnEncodeEnum().
#define NULL_VALUE 1
Referenced by asnEncodeEnum().
Function Documentation
int asnEncodeEnum (byte * buffer, long value)
Encode an enumeration value with tag and length.
Encode an enumeration (C-type long) with tag and length into a buffer. This function does the same as the function asnEncodeInteger except the encoding value of the tag. buffer is the buffer to fill with the resulting encoding, value is the enumeration value to encode.
Returns
If an error occures, the function returns -1, or the length of the result in buffer otherwise.
See also
asnDecodeEnum, asnReadEnum, asnWriteEnum
Note
Restriction: The Integer has to be less than 2^31.
References asnEncodeLength(), asnEncodeTag(), asnENUMERATED, asnPRIMITIVE, asnUNIVERSAL, FF_VALUE, IGNORE_VALUE, and NULL_VALUE.
Referenced by asnWriteEnum().
int asnEncodeEnumValue (byte * buffer, long value)
Encode an enumeration value as an integer with tag and length.
Encode an enumeration (C-type long) with tag and length into a buffer. This function does the same as the function asnEncodeIntegerValue except the encoding value of the tag. buffer is the buffer to fill with the resulting encoding, value is the enumeration value to encode.
Returns
If an error occures, the function returns -1, or the length of the result in buffer otherwise.
See also
asnDecodeEnum, asnReadEnum, asnWriteEnum
References asnEncodeIntegerValue().