AKASN.1: src/enumrd.c File Reference
enumrd.c File Reference
#include <string.h>
#include "akasn1.h"
Functions
int asnReadEnumTL (long *value)
Read an enumeration value from an ASN.1-File (with tag and length)
int asnReadEnumL (long *value)
Read an enumeration value including the length from an ASN.1-File.
int asnReadEnum (long *value, int length)
Read only the enumeration value w/o the tag and length.
Function Documentation
int asnReadEnum (long * value, int length)
Read only the enumeration value w/o the tag and length.
Read only the enumeration value from the opened ASN.1 file, without the tag and the length. These had to be read prior. value is a pointer to the buffer to encode the value in. length is the number of bytes to read from the file.
Returns
If an error occures, the function returns -1, or the length of the encoded enumeration value otherwise.
See also
asnDecodeEnum, asnEncodeEnum, asnWriteEnum, asnReadEnumL, asnReadEnumTL
References asnDecodeEnum(), and asnRead().
Referenced by asnReadEnumL().
int asnReadEnumL (long * value)
Read an enumeration value including the length from an ASN.1-File.
Read an enumeration value from the opened ASN.1 file, including the length. The type tag may have been read prior. value is the variable to fill with the result.
Returns
If an error occures, the function returns -1, or 0 otherwise.
See also
asnDecodeEnum, asnEncodeEnum, asnWriteEnum, asnReadEnum, sasnReadEnumTL
References asnReadEnum(), and asnReadLength().
Referenced by asnReadEnumTL().
int asnReadEnumTL (long * value)
Read an enumeration value from an ASN.1-File (with tag and length)
Read an enumeration value from the opened ASN.1 file, including the tag and the length of the encoding. value is the variable to fill with the result.
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not of type enumeration. 0 is return if no error occured.
See also
asnDecodeEnum, asnEncodeEnum, asnWriteEnum, asnReadEnumL
References asnDecodeTag(), asnENUMERATED, asnReadEnumL(), asnReadTag(), asnSkipFile(), and asnUNIVERSAL.