AKASN.1: src/extrd.c File Reference
extrd.c File Reference
#include <assert.h>
#include <string.h>
#include <unistd.h>
#include "akasn1.h"
Functions
long asnReadExternalBPFile (byte *param, long *parlen, long maxplen, char *poid, int outfd, long *datalen, char *doid, byte *dpc)
Read an X.400 EXTERNAL body part from an ASN.1 file.
Function Documentation
long asnReadExternalBPFile (byte * param, long * parlen, long maxplen, char * poid, int outfd, long * datalen, char * doid, byte * dpc)
Read an X.400 EXTERNAL body part from an ASN.1 file.
Read an X.400 EXTERNAL body part from an ASN.1 file. Only direct-reference (oid) and encoding (0, 1, 2) are supported.
Returns
If an error occures, the function returns -1, or the number of bytes read otherwise.
See also
asnWriteExternalBPFile
References asnCONTEXT, asnDecodeTag(), asnEXTERNAL, asnfd, asnRead(), asnReadOid(), asnReadTagAndLength(), asnSEQUENCE, asnSkipFile(), and asnUNIVERSAL.