AKASN.1: src/extwr.c File Reference
extwr.c File Reference
#include <stdio.h>
#include <assert.h>
#include <unistd.h>
#include "akasn1.h"
Functions
long asnWriteExternalBPFile (byte *param, long parlen, char *poid, byte pet, byte pcon, int infd, char *doid, byte det, byte dcon)
Write an X.400 EXTERNAL body part to a file.
Function Documentation
long asnWriteExternalBPFile (byte * param, long parlen, char * poid, byte pet, byte pcon, int infd, char * doid, byte det, byte dcon)
Write an X.400 EXTERNAL body part to a file.
Write an X.400 EXTERNAL body part to a file. Only direct-reference (oid) and encoding (0, 1, 2) are supported. param is a pointer to the encoded (!) parameter part or 0. parlen is the length of the data in param or 0. poid is the OID of the parameter part or 0. pet is the type for the CHOICE-Tag (0,1,2) of the parameter part. pcon is a flag whether the parameters are constructed or not. infd is the File descriptor to the (encoded) data. doid is the OID of the data part. det is the type for the CHOICE-Tag (0,1,2) of the data part. dcon is a flag whether the parameters are constructed or primitive.
Returns
If an error occures, the function returns -1, or the length of theencoding otherwise.
See also
asnReadExternalBPFile
References asnCONSTRUCTED, asnCONTEXT, asnEncodeLength(), asnEncodeTag(), asnSEQUENCE, asnUNIVERSAL, and asnWrite().