AKASN.1: src/ia5enc.c File Reference
ia5enc.c File Reference
#include <string.h>
#include <ctype.h>
#include "akasn1.h"
Functions
int asnEncodeIA5 (char *value, byte *buffer, int *length)
Encode an IA5-String with tag and length.
Function Documentation
int asnEncodeIA5 (char * value, byte * buffer, int * length)
Encode an IA5-String with tag and length.
Encode an IA5-String with tag and length into a buffer. value is a 0-terminated C-string. buffer is a buffer in which the encoding of the tag and the length will be done. The length of the encoding in buffer will be returned in length.
Returns
If an error occures, the function returns -1, -2 of the value is not a legal IA5-String or the length of the result in buffer otherwise.
Note
Restriction: The length of the string has to be less than MAXINT.
See also
asnDecodeIA5, asnReadIA5, asnWriteIA5
References asnEncodeLength(), asnEncodeTag(), asnIA5STRING, asnPRIMITIVE, and asnUNIVERSAL.
Referenced by asnWriteIA5().