AKASN.1: src/ia5rd.c File Reference
ia5rd.c File Reference
#include "akasn1.h"
Functions
int asnReadIA5TL (char *value, int maxlen)
Read an IA5-String from the opened ASN.1 file (with tag and length)
int asnReadIA5L (char *value, int maxlen)
Read an IA5-String including the length from an ASN.1-File.
int asnReadIA5 (char *value, int length, int maxlen)
Read only the IA5-String w/o the tag and length.
Function Documentation
int asnReadIA5 (char * value, int length, int maxlen)
Read only the IA5-String w/o the tag and length.
Read only the IA5-String from the opened ASN.1 file, without the tag and the length. These had to be read prior. value is a pointer to the buffer to encode the string in. length is the number of bytes to read from the file. maxlen is maximum number of characters to be read.
Returns
If an error occures, the function returns -1. Otherwise, the number of characters read is returned.
Note
Restriction: The length of the string has to be less than MAXINT.
See also
asnDecodeIA5, asnEncodeIA5, asnWriteIA5, asnReadIA5L, asnReadIA5TL
References asnDecodeIA5(), asnRead(), and asnSkipFile().
Referenced by asnReadIA5L().
int asnReadIA5L (char * value, int maxlen)
Read an IA5-String including the length from an ASN.1-File.
Read an IA5-String from the opened ASN.1 file, including the length. The type tag may have been read prior. value is the variable to fill with the result. maxlen is maximum number of characters to be read.
Returns
If an error occures, the function returns -1. Otherwise, the number of characters read is returned.
Note
Restriction: The length of the string has to be less than MAXINT.
See also
asnDecodeIA5, asnEncodeIA5, asnWriteIA5, asnReadIA5, asnReadIA5TL
References asnReadIA5(), and asnReadLength().
Referenced by asnReadIA5TL().
int asnReadIA5TL (char * value, int maxlen)
Read an IA5-String from the opened ASN.1 file (with tag and length)
Read an IA5-String from the opened ASN.1 file, including the tag and the length of the encoding. value is the variable to fill with the result, maxlen is the maximum number of characters to be read (mostly the size of value).
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not of type IA5-String. Otherwise, the number of characters read is returned.
Note
Restriction: The length of the string has to be less than MAXINT.
See also
asnDecodeIA5, asnEncodeIA5, asnWriteIA5, asnReadIA5L
References asnDecodeTag(), asnIA5STRING, asnReadIA5L(), asnReadTag(), asnSkipFile(), and asnUNIVERSAL.