AKASN.1: src/intenc.c File Reference
intenc.c File Reference
#include "akasn1.h"
Macros
#define IGNORE_VALUE 0
#define NULL_VALUE 1
#define FF_VALUE 2
Functions
int asnEncodeInteger (byte *buffer, long value)
Encode an integer value with tag and length.
int asnEncodeIntegerValue (byte *buffer, long value)
Encode an integer value with tag (no length!)
Macro Definition Documentation
#define FF_VALUE 2
#define IGNORE_VALUE 0
#define NULL_VALUE 1
Function Documentation
int asnEncodeInteger (byte * buffer, long value)
Encode an integer value with tag and length.
Encode an Integer (C-type long) with tag and length into a buffer. buffer is the buffer to fill with the resulting encoding, value is the integer value to encode.
Returns
If an error occures, the function returns -1, or the length of the result in buffer otherwise.
Note
Restriction: The Integer has to be less than 2^31.
See also
asnDecodeInteger, asnReadInteger, asnWriteInteger
References asnEncodeTag(), asnINTEGER, asnPRIMITIVE, and asnUNIVERSAL.
Referenced by asnWriteInteger().
int asnEncodeIntegerValue (byte * buffer, long value)
Encode an integer value with tag (no length!)
Encode an Integer (C-type long) with tag but without the length into a buffer. buffer is the buffer to fill with the resulting encoding, value is the integer value to encode.
Returns
If an error occures, the function returns -1, or the length of the result in buffer otherwise.
Note
Restriction: The Integer has to be less than 2^31.
See also
asnDecodeInteger, asnReadInteger, asnWriteInteger
Referenced by asnEncodeEnumValue().