AKASN.1: src/intrd.c File Reference
intrd.c File Reference
#include <string.h>
#include "akasn1.h"
Functions
int asnReadIntegerTL (long *value)
Read an integer value from an ASN.1-File (with tag and length)
int asnReadIntegerL (long *value)
Read an integer value including the length from an ASN.1-File.
int asnReadInteger (long *value, int length)
Read only a integer value w/o the tag and length.
Function Documentation
int asnReadInteger (long * value, int length)
Read only a integer value w/o the tag and length.
Read only an ineteger value from the opened ASN.1 file, without the tag and the length. These had to be read prior. value is a pointer to the buffer to encode the value in. length is the number of bytes to read from the file.
Returns
If an error occures, the function returns -1, or the length of the encoded integer value otherwise.
Note
Restriction: The Integer has to be less than 2^31.
See also
asnDecodeInteger, asnEncodeInteger, asnWriteInteger, asnReadIntegerL, asnReadIntegerTL
References asnDecodeInteger(), and asnRead().
Referenced by asnReadIntegerL().
int asnReadIntegerL (long * value)
Read an integer value including the length from an ASN.1-File.
Read an integer value from the opened ASN.1 file, including the length. The type tag must have been read prior. value is the variable to fill with the result.
Returns
If an error occures, the function returns -1, or 0 otherwise.
Note
Restriction: The Integer has to be less than 2^31.
See also
asnDecodeInteger, asnEncodeInteger, asnWriteInteger, asnReadInteger, asnReadIntegerTL
References asnReadInteger(), and asnReadLength().
Referenced by asnReadIntegerTL().
int asnReadIntegerTL (long * value)
Read an integer value from an ASN.1-File (with tag and length)
Read an integer value from the opened ASN.1 file, including the tag and the length of the encoding. value is the variable to fill with the result.
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not of type integer. 0 is return if no error occured.
Note
Restriction: The Integer has to be less than 2^31.
See also
asnDecodeInteger, asnEncodeInteger, asnWriteInteger, asnReadIntegerL
References asnDecodeTag(), asnINTEGER, asnReadIntegerL(), asnReadTag(), asnSkipFile(), and asnUNIVERSAL.