AKASN.1: src/lenenc.c File Reference
lenenc.c File Reference
#include <stdio.h>
#include "akasn1.h"
Functions
int asnEncodeLength (byte *buffer, long length)
Encode a "length" field.
Function Documentation
int asnEncodeLength (byte * buffer, long length)
Encode a "length" field.
Encode a length field length into the buffer.
Returns
If an error occures, the function returns -1, or the length of the encoding in buffer otherwise.
Note
Restriction: supports only length between 0 and MAXLONG.
See also
asnDecodeLength, asnReadLength, asnWriteLength
References asnENDCONTENTS, and asnINDEFINITE.
Referenced by _asnWriteOctetFile(), asnEncodeBoolean(), asnEncodeEnum(), asnEncodeIA5(), asnEncodeOctet(), asnWriteExternalBPFile(), and asnWriteLength().