AKASN.1: src/lenrd.c File Reference
lenrd.c File Reference
#include "akasn1.h"
Functions
int asnReadLength (long *length)
Read a "length" field from the opened ASN.1 file.
Function Documentation
int asnReadLength (long * length)
Read a "length" field from the opened ASN.1 file.
This function reads the ASN.1 length field from an opened file. length is a pointer to a long variable which will get the result.
Returns
If an error occures, the function returns -1, or the length of the encoding read from the file otherwise.
Note
Restriction: supports only length between 0 and MAXLONG.
See also
asnOpenReadFile, asnOpenWriteFile, asnEncodeLength, asnDecodeLength, asnWriteLength
References asnINDEFINITE, and asnRead().
Referenced by asnReadBooleanL(), asnReadEnumL(), asnReadIA5L(), asnReadIntegerL(), asnReadOctet(), asnReadOctetFile(), asnReadOctetFileL(), asnReadOctetL(), asnReadOidL(), and asnReadTagAndLength().