AKASN.1: src/nullrd.c File Reference
nullrd.c File Reference
#include "akasn1.h"
Functions
int asnReadNullTL (void)
Read a Null value with tag and length.
int asnReadNullL (void)
Read a Null value with length field.
Function Documentation
int asnReadNullL (void)
Read a Null value with length field.
Read a Null-value (with length) from the opened ASN.1 file without the tag. This function does nothing more than read one byte of the input stream and ignore the length-field which should be 0.
Returns
If an error occures, the function returns -1, or the number of bytes read otherwise.
See also
asnEncodeNull, asnReadNullTL, asnWriteNull
References asnSkipFile().
Referenced by asnReadNullTL().
int asnReadNullTL (void)
Read a Null value with tag and length.
Read a Null value from an opened ASN.1 file, including the tag and the length.
Returns
If an error occures, the function returns -1, -2 if the value read is not a Null value or the number of bytes read otherwise.
See also
asnEncodeNull, asnReadNullL, asnWriteNull
References asnDecodeTag(), asnNULLVALUE, asnReadNullL(), asnReadTag(), asnSkipFile(), and asnUNIVERSAL.