AKASN.1: src/octrd.c File Reference
octrd.c File Reference
#include <assert.h>
#include <unistd.h>
#include "akasn1.h"
Functions
int asnReadOctetTL (byte *value, int maxlen)
Read an octet string from an ASN.1-File (with tag and length)
int asnReadOctetL (byte *value, int maxlen, byte pc)
Read an octet string from an ASN.1-File (with the length)
int asnReadOctet (byte *value, int length, int maxlen, byte pc)
Read an octet string from an ASN.1-File (w/o the tag and length)
long asnReadOctetFileTL (int outfile)
Read an octet string from an ASN.1-File and write it to another file.
long asnReadOctetFileL (int outfile, byte pc)
Read an octet string from an ASN.1-File (with the tag) and write it to another file.
long asnReadOctetFile (int outfile, byte pc, long length)
Read an octet string from an ASN.1-File (w/o the tag and the length) and write it to another file.
Function Documentation
int asnReadOctet (byte * value, int length, int maxlen, byte pc)
Read an octet string from an ASN.1-File (w/o the tag and length)
Read an octet string from the opened ASN.1 file (only the data). The tag and the length must have been read prior to the call of this function. value is the variable to fill with the result. length is the length of the data to be read. maxlen is the maximum number of bytes to be read. pc is a flag whether the encoding is primitive (asnPRIMITIVE) or constructed (asnCONSTRUCTED).
Returns
If an error occures, the function returns -1. Otherwise, the number of bytes read is returned.
Note
The maximum number of bytes has to be less than MAXINT.
See also
asnDecodeOctet, asnEncodeOctet, asnWriteOctet, asnReadOctetTL, asnReadOctetFileTL
References asnCONSTRUCTED, asnDecodeOctet(), asnDecodeTag(), asnRead(), asnReadLength(), asnReadOctet(), asnReadTag(), and asnSkipFile().
Referenced by asnReadOctet(), and asnReadOctetL().
long asnReadOctetFile (int outfile, byte pc, long length)
Read an octet string from an ASN.1-File (w/o the tag and the length) and write it to another file.
Read an octet string from the opened ASN.1 file (without the tag and the length) and write it to another open file outfile. pc is a flag whether the encoding is primitive (asnPRIMITIVE) or constructed (asnCONSTRUCTED). length is the number of bytes to be read.
Returns
If an error occures, the function returns -1. Otherwise, the number of bytes read is returned.
Note
The maximum number of bytes has to be less than MAXINT.
See also
asnDecodeOctet, asnEncodeOctet, asnWriteOctet, asnReadOctetTL, asnReadOctetFile
References asnCONSTRUCTED, asnDecodeTag(), asnfd, asnReadLength(), asnReadOctetFile(), and asnReadTag().
Referenced by asnReadOctetFile(), and asnReadOctetFileL().
long asnReadOctetFileL (int outfile, byte pc)
Read an octet string from an ASN.1-File (with the tag) and write it to another file.
Read an octet string from the opened ASN.1 file (and the length) and write it to another open file outfile. pc is a flag whether the encoding is primitive (asnPRIMITIVE) or constructed (asnCONSTRUCTED).
Returns
If an error occures, the function returns -1. Otherwise, the number of bytes read is returned.
Note
The maximum number of bytes has to be less than MAXINT.
See also
asnDecodeOctet, asnEncodeOctet, asnWriteOctet, asnReadOctetTL, asnReadOctetFile
References asnReadLength(), and asnReadOctetFile().
Referenced by asnReadOctetFileTL().
long asnReadOctetFileTL (int outfile)
Read an octet string from an ASN.1-File and write it to another file.
Read an octet string from the opened ASN.1 file (including the tag and the length) and write it to another open file outfile.
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not an octet string. Otherwise, the number of bytes read is returned.
Note
The maximum number of bytes has to be less than MAXINT.
See also
asnDecodeOctet, asnEncodeOctet, asnWriteOctet, asnReadOctetTL, asnReadOctetFile
References asnDecodeTag(), asnGENERALSTRING, asnGRAPHICSTRING, asnIA5STRING, asnNUMERICSTRING, asnOCTETSTRING, asnPRINTABLESTRING, asnReadOctetFileL(), asnReadTag(), asnSkipFile(), asnTELETEXSTRING, asnUNIVERSAL, asnVIDEOTEXSTRING, and asnVISIBLESTRING.
int asnReadOctetL (byte * value, int maxlen, byte pc)
Read an octet string from an ASN.1-File (with the length)
Read an octet string from the opened ASN.1 file, including the length of the encoding. The tag must have been read prior to the call of this function. value is the variable to fill with the result. maxlen is the maximum number of bytes to be read. pc is a flag whether the encoding is primitive (asnPRIMITIVE) or constructed (asnCONSTRUCTED).
Returns
If an error occures, the function returns -1. Otherwise, the number of bytes read is returned.
Note
The maximum number of bytes has to be less than MAXINT.
See also
asnDecodeOctet, asnEncodeOctet, asnWriteOctet, asnReadOctet, asnReadOctetFileTL
References asnReadLength(), and asnReadOctet().
Referenced by asnReadOctetTL().
int asnReadOctetTL (byte * value, int maxlen)
Read an octet string from an ASN.1-File (with tag and length)
Read an octet string from the opened ASN.1 file, including the tag and the length of the encoding. value is the variable to fill with the result. maxlen is the maximum number of bytes to be read.
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not an octet string. Otherwise, the number of bytes read is returned.
Note
The maximum number of bytes has to be less than MAXINT.
See also
asnDecodeOctet, asnEncodeOctet, asnWriteOctet, asnReadOctetL, asnReadOctetFileTL
References asnDecodeTag(), asnGENERALSTRING, asnGRAPHICSTRING, asnIA5STRING, asnNUMERICSTRING, asnOCTETSTRING, asnPRINTABLESTRING, asnReadOctetL(), asnReadTag(), asnSkipFile(), asnTELETEXSTRING, asnUNIVERSAL, asnVIDEOTEXSTRING, and asnVISIBLESTRING.