AKASN.1: src/octwr.c File Reference
octwr.c File Reference
#include <unistd.h>
#include "akasn1.h"
Functions
int _asnWriteOctet (byte *value, int length, byte tag)
Write an octet string into an ASN.1 file.
int _asnWriteOctetFile (int infd, long length, byte tag)
Read data from a file and write it as an octet string into an ASN.1 file.
Function Documentation
int _asnWriteOctet (byte * value, int length, byte tag)
Write an octet string into an ASN.1 file.
Write an octet string into an opened ASN.1 file. value is the data value to be written. length is the number of bytes to be encoded. Macros for each individual octet or other string type actually map to this function which does the writing. See akasn1.h for further details on writing of octet and other strings.
Returns
If an error occures, the function returns -1 or the number of bytes written to the file otherwise.
Note
Restriction: The length of the data has to be less than MAXINT.
See also
asnReadOctet, asnWriteOctetFile
References asnEncodeOctet(), asnGENERALSTRING, asnGRAPHICSTRING, asnIA5STRING, asnNUMERICSTRING, asnOCTETSTRING, asnPRINTABLESTRING, asnTELETEXSTRING, asnVIDEOTEXSTRING, asnVISIBLESTRING, and asnWrite().
int _asnWriteOctetFile (int infd, long length, byte tag)
Read data from a file and write it as an octet string into an ASN.1 file.
Read data from an open file infd and write it as an octet string to an opened ASN.1 file. length is the number of bytes to encode from the original file. Macros for each individual octet or other string type actually map to this function, which does the writing. See akasn1.h for further details on writing of octet and other strings.
Returns
If an error occures, the function returns -1 or the number of bytes written to the file otherwise.
Note
Restriction: The length of the data has to be less than MAXINT.
See also
asnReadOctet, asnWriteOctetFile
References asnEncodeLength(), asnEncodeTag(), asnGENERALSTRING, asnGRAPHICSTRING, asnIA5STRING, asnNUMERICSTRING, asnOCTETSTRING, asnPRIMITIVE, asnPRINTABLESTRING, asnTELETEXSTRING, asnUNIVERSAL, asnVIDEOTEXSTRING, asnVISIBLESTRING, and asnWrite().