AKASN.1: src/oidrd.c File Reference
oidrd.c File Reference
#include <string.h>
#include "akasn1.h"
Functions
int asnReadOidTL (char *id)
Read an object identifier from an ASN.1-File (with tag and length)
int asnReadOidL (char *id)
Read an object identifier from an ASN.1-File (with length)
int asnReadOid (char *id, int length)
Read an object identifier from an ASN.1-File (w/o tag and length)
Function Documentation
int asnReadOid (char * id, int length)
Read an object identifier from an ASN.1-File (w/o tag and length)
Read an object identifier from the opened ASN.1 file. length is the number of bytes to be read. id is the variable to fill with the result.
Returns
If an error occures, the function returns -1. Otherwise, the length of the resulting object identifier string is returned.
Note
Restriction: The maximum length has to be less or equal 127 octets and the maximum number of subidentifiers is 10. The number of oid's has to be equal or greater than 2. Supports only subid's less or equal 16383.
See also
asnDecodeOID, asnEncodeOID, asnReadOIDTL, asnWriteOID
References asnDecodeOid(), and asnRead().
Referenced by asnReadExternalBPFile(), and asnReadOidL().
int asnReadOidL (char * id)
Read an object identifier from an ASN.1-File (with length)
Read an object identifier from the opened ASN.1 file, including the length of the encoding. id is the variable to fill with the result.
Returns
If an error occures, the function returns -1. Otherwise, the length of the resulting object identifier string is returned.
Note
Restriction: The maximum length has to be less or equal 127 octets and the maximum number of subidentifiers is 10. The number of oid's has to be equal or greater than 2. Supports only subid's less or equal 16383.
See also
asnDecodeOID, asnEncodeOID, asnReadOID, asnWriteOID
References asnReadLength(), and asnReadOid().
Referenced by asnReadOidTL().
int asnReadOidTL (char * id)
Read an object identifier from an ASN.1-File (with tag and length)
Read an object identifier from the opened ASN.1 file, including the tag and the length of the encoding. id is the variable to fill with the result.
Returns
If an error occures, the function returns -1. -2 is returned if the value read is not an object identifier. Otherwise, the length of the resulting object identifier string is returned.
Note
Restriction: The maximum length has to be less or equal 127 octets and the maximum number of subidentifiers is 10. The number of oid's has to be equal or greater than 2. Supports only subid's less or equal 16383.
See also
asnDecodeOID, asnEncodeOID, asnReadOIDL, asnWriteOID
References asnDecodeTag(), asnOBJECTID, asnReadOidL(), asnReadTag(), asnSkipFile(), and asnUNIVERSAL.