AKASN.1: src/readbuf.c File Reference
readbuf.c File Reference
#include <unistd.h>
#include "akasn1.h"
Functions
int asnRead (byte *buffer, uint length)
Read some data from the ASN.1 file.
Function Documentation
int asnRead (byte * buffer, uint length)
Read some data from the ASN.1 file.
Read some data from the opened ASN.1 file. buffer is the buffer to be filled with the data, length is the number of bytes to be read.
Returns
If an error occures, the function returns -1, 0 at EOF, or the number of bytes read otherwise.
See also
asnOpenReadFile, asnWrite
References asnfd.
Referenced by asnIsEOC(), asnReadBoolean(), asnReadEnum(), asnReadExternalBPFile(), asnReadIA5(), asnReadInteger(), asnReadLength(), asnReadOctet(), asnReadOid(), and asnReadTag().