AKASN.1: src/skipfile.c File Reference
skipfile.c File Reference
#include <sys/file.h>
#include <unistd.h>
#include "akasn1.h"
Functions
int asnSkipFile (long length)
Skip a portion of the opened ASN.1 file.
Function Documentation
int asnSkipFile (long length)
Skip a portion of the opened ASN.1 file.
This function skips length bytes of the data in the opened ASN.1 file.
Returns
If an error occures, the function returns -1, or 0 otherwise.
See also
asnFtell, asnFSeek, asnOpenReadFile, asnOpenWriteFile
References asnfd.
Referenced by asnReadBooleanTL(), asnReadEnumTL(), asnReadExternalBPFile(), asnReadIA5(), asnReadIA5TL(), asnReadIntegerTL(), asnReadNullL(), asnReadNullTL(), asnReadOctet(), asnReadOctetFileTL(), asnReadOctetTL(), and asnReadOidTL().