AKASN.1: src/tagdec.c File Reference
tagdec.c File Reference
#include "akasn1.h"
Functions
int asnDecodeTag (byte *clasS, byte *pc, byte *tagnum, byte *buf)
Decode an ASN.1 tag.
Function Documentation
int asnDecodeTag (byte * clasS, byte * pc, byte * tagnum, byte * buf)
Decode an ASN.1 tag.
Decode an ASN.1 tag value. class is a pointer to a variable to store the class value (asnUNIVERSAL , asnAPPLICATION , asnCONTEXT, asnPRIVATE) in. pc is a pointer to a variable to indicate wether the data following the tag is constructed or primitive (asnPRIMITIVE , asnCONSTRUCTED). tagnum is a pointer to a variable to store the tag number in. buffer is the buffer which contains the tag to decode.
Returns
If an error occures, the function returns -1, or the number of decoded bytes otherwise.
See also
asnEncodeTag, asnReadTag, asnReadTagAndLength, asnWriteTag
Referenced by asnReadBooleanTL(), asnReadEnumTL(), asnReadExternalBPFile(), asnReadIA5TL(), asnReadIntegerTL(), asnReadNullTL(), asnReadOctet(), asnReadOctetFile(), asnReadOctetFileTL(), asnReadOctetTL(), and asnReadOidTL().