AKASN.1: src/tagenc.c File Reference
tagenc.c File Reference
#include "akasn1.h"
Functions
int asnEncodeTag (byte *buf, byte clasS, byte pc, byte tag)
Encode an ASN.1 tag.
Function Documentation
int asnEncodeTag (byte * buf, byte clasS, byte pc, byte tag)
Encode an ASN.1 tag.
Encode an ASN.1 tag value. class is the class of the tag (asnUNIVERSAL , asnAPPLICATION , asnCONTEXT , asnPRIVATE). pc is a flag to indicate wether the data following the tag is constructed or primitive (asnPRIMITIVE , asnCONSTRUCTED). tag is the number of the tag. buffer is the buffer which will get the resulting encoding.
Returns
If an error occures, the function returns -1, or the number of encoded bytes otherwise.
See also
asnDecodeTag, asnReadTag, asnReadTagAndLength, asnWriteTag
Referenced by _asnWriteOctetFile(), asnEncodeBoolean(), asnEncodeEnum(), asnEncodeIA5(), asnEncodeInteger(), asnEncodeNull(), asnEncodeOctet(), asnWriteExternalBPFile(), and asnWriteTag().