AKASN.1: src/taglenrd.c File Reference
taglenrd.c File Reference
#include "akasn1.h"
Functions
long asnReadTagAndLength (byte *buffer, long *length)
Read a tag and a length from the opened ASN.1 file.
Function Documentation
long asnReadTagAndLength (byte * buffer, long * length)
Read a tag and a length from the opened ASN.1 file.
Read a tag and a length from the opened ASN.1 file. buffer is a pointer to the buffer for the read tag. length is a pointer to a variable, which will get the decoded length.
Returns
If an error occures, the function returns -1, or 0 otherwise.
See also
asnReadTag, asnReadLength
References asnReadLength(), and asnReadTag().
Referenced by asnReadExternalBPFile().