AKASN.1: src/tagrd.c File Reference
tagrd.c File Reference
#include "akasn1.h"
Functions
int asnReadTag (byte *buffer)
Read a tag from the opened ASN.1 file.
Function Documentation
int asnReadTag (byte * buffer)
Read a tag from the opened ASN.1 file.
Read a tag from the opened ASN.1 file. buffer is a pointer to the buffer which will get the resulting tag encoding.
Returns
If an error occures, the function returns -1, or the size of the tag in buffer otherwise.
See also
asnOpenReadFile, asnRead, asnDecodeTag
References asnRead().
Referenced by asnReadBooleanTL(), asnReadEnumTL(), asnReadIA5TL(), asnReadIntegerTL(), asnReadNullTL(), asnReadOctet(), asnReadOctetFile(), asnReadOctetFileTL(), asnReadOctetTL(), asnReadOidTL(), and asnReadTagAndLength().