AKASN.1: src/writebuf.c File Reference
writebuf.c File Reference
#include <unistd.h>
#include "akasn1.h"
Functions
int asnWrite (byte *buffer, uint len)
Write a buffer to the opened ASN.1 file.
Function Documentation
int asnWrite (byte * buffer, uint len)
Write a buffer to the opened ASN.1 file.
Write a length bytes of the buffer buffer to the opened ASN.1 file.
Returns
If an error occures, the function returns -1, or the number of bytes written otherwise.
See also
asnOpenReadFile, asnOpenWriteFile
References asnfd.
Referenced by _asnWriteOctet(), _asnWriteOctetFile(), asnWriteBoolean(), asnWriteEnum(), asnWriteExternalBPFile(), asnWriteIA5(), asnWriteInteger(), asnWriteLength(), asnWriteNull(), asnWriteOid(), and asnWriteTag().